package Categories;

public enum JobTitle {

    ARCHITECT,
    THERAPIST,
    COFFEE_SHOP_OWNER,
    ELECTRONIC_REPAIRER,
    RACE_DRIVER,
    STAY_AT_HOME,
    LOCAL_FOOD_CRITIC,
    MICHELIN_STAR_CHEF
}
